GET http://localhost:9090/api/tasks
Accept: application/json
###

POST http://localhost:9090/api/tasks
Content-Type: application/json

{
  "title": "testowe zadanie",
  "description": "testowy opis",
  "author": "Jan Testowy"
}
###

GET http://localhost:9090/api/tasks/1
Accept: application/json
###

DELETE http://localhost:9090/api/tasks/3
###

PUT http://localhost:9090/api/tasks
###